Repository COSC481W-2022Winter/capstone-gigabites, pull requests merged in 2022-02, with the labels that each got.

#8 Fix bug of file location in package.json
  server/package.json
Labels: bug

#10 SignUP User Interface and sets up Routing
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/config.json
  client/src/pages/index.js
  client/src/pages/profile.js
  client/src/pages/signup.js
  server/index.js
  server/models/Users.js
  server/package-lock.json
  server/package.json
Labels: enhancement, sprint1

#11 fix: Remove warnings
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/signup.js
Labels: bug, low-priority, sprint1, node, react

#12 feat: Add login ui
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/login.js
Labels: enhancement, high-priority, sprint1, node, react

#14 feat: Password, encryption, transfer
  client/src/pages/login.js
  server/index.js
  server/models/Users.js
Labels: enhancement, high-priority, sprint1, node, mongodb, express, react

#15 feat:redirect forgot password and alerts
  client/src/App.js
  client/src/pages/login.js
  client/src/pages/passwordReset.js
  server/index.js
Labels: bug, enhancement, sprint1, node, react

#13 Feat: Password Strength Checker and Remove Unused Code
  .gitignore
  client/src/App.css
  client/src/pages/login.js
  client/src/pages/passwordReset.js
  client/src/pages/signup.js
  server/index.js
Labels: bug, enhancement, sprint1
