Repository COSC481W-2022Winter/capstone-gigabites, pull requests merged in 2022-04, with the labels that each got.

#55 feat: Added dynamic rows to createRecipe page
  client/src/pages/createRecipe.js
  server/index.js
  server/models/Ingredients.js
  server/models/Recipes.js
Labels: bug, documentation, enhancement, mongodb, react, sprint3

#59 feat: About Us page
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/About-Us.js
  server/index.js
  server/models/Developers.js
Labels: enhancement, mongodb, express, react, sprint3

#60 feat: redirect from creating a recipe and modify create recipe page
  client/src/App.js
  client/src/pages/createRecipe.js
  client/src/pages/recipeRedirect.js
  server/index.js
  server/models/Recipes.js
Labels: bug, documentation, enhancement, mongodb, react, sprint3

#62 feat: view information about website developers
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/About-Us.js
  server/index.js
  server/models/Developers.js
Labels: enhancement, mongodb, react, sprint3, Main PBI

#61 fix: Create recipe bug fixes
  client/src/pages/createRecipe.js
Labels: enhancement, low-priority, react, bug fix, sprint3

#57 feat: Adds working view recipe page
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/recipe.js
  server/index.js
  server/models/Ingredients.js
Labels: bug, enhancement, mongodb, express, react, sprint3, styles

#64 fix: Fixed bug for negative and zero numbers on createRecipe
  client/src/pages/createRecipe.js
  server/models/Recipes.js
Labels: low-priority, react, bug fix, sprint3, Waiting on review

#56 feat: Ability to upload profile picture
  client/src/App.css
  client/src/App.js
  client/src/pages/EditProfileTransition.js
  client/src/pages/editProfile.js
  client/src/pages/login.js
  server/index.js
Labels: bug, enhancement, mongodb, express, react, sprint3, styles

#63 feat: view uploaded recipes
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/recipe.js
  server/index.js
  server/models/Ingredients.js
Labels: documentation, enhancement, mongodb, express, react, sprint3, styles, Main PBI, Waiting on review

#66 fix: editProfile bug fix
  client/src/pages/About-Us.js
  client/src/pages/editProfile.js
Labels: react, bug fix, sprint3

#65 feat: Ability to edit user profile
  client/src/App.css
  client/src/App.js
  client/src/pages/About-Us.js
  client/src/pages/EditProfileTransition.js
  client/src/pages/createRecipe.js
  client/src/pages/editProfile.js
  client/src/pages/login.js
  client/src/pages/profile.js
  server/index.js
Labels: documentation, enhancement, high-priority, mongodb, express, react, sprint3, Main PBI

#67 fix: Various bug fixes
  client/src/pages/login.js
  client/src/pages/recipeRedirect.js
  server/index.js
Labels: high-priority, react, bug fix, sprint3

#68 fix: Ingredient row fix
  client/src/pages/createRecipe.js
Labels: low-priority, react, bug fix, sprint3

#58 feat: upload recipe page modifications
  client/src/App.js
  client/src/pages/createRecipe.js
  client/src/pages/login.js
  client/src/pages/recipeRedirect.js
  server/index.js
  server/models/Recipes.js
Labels: enhancement, mongodb, express, react, sprint3, styles, Main PBI

#69 refactor: Major config file refactor
  .gitignore
  client/src/pages/About-Us.js
  client/src/pages/EditProfileTransition.js
  client/src/pages/config.json
  client/src/pages/createRecipe.js
  client/src/pages/editProfile.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/recipe.js
  client/src/pages/recipeRedirect.js
  client/src/pages/signup.js
  server/index.js
Labels: enhancement, high-priority, react, bug fix

#70 feat: Added background image to homepage
  client/src/App.css
  client/src/pages/About-Us.js
  client/src/pages/img/home.jpg
  client/src/pages/index.js
Labels: enhancement, react, bug fix, styles, Waiting on review, Sprint4

#77 refactor: Recipe page functionality
  client/src/App.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/recipe.js
Labels: enhancement, high-priority, express, react, bug fix, Waiting on review, Sprint4

#76 feat: Reset forgotten passwords with user's username
  client/src/App.css
  client/src/App.js
  client/src/pages/editProfile.js
  client/src/pages/forgotPassword.js
  client/src/pages/login.js
  client/src/pages/passwordReset.js
  client/src/pages/signup.js
  server/index.js
  server/models/Users.js
Labels: documentation, enhancement, mongodb, express, react, Waiting on review, Sprint4

#79 refractor: Need necessary functions from main
  client/src/App.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/recipe.js
Labels: documentation, enhancement, mongodb, express, react, styles, Sprint4

#82 feat: added a success message popup for recipe redirect
  client/src/pages/recipe.js
Labels: enhancement, react, bug fix, Sprint4

#78 feat: Implements email server to reset user's forgotten password
  client/src/App.css
  client/src/App.js
  client/src/pages/editProfile.js
  client/src/pages/forgotPassword.js
  client/src/pages/login.js
  client/src/pages/passwordReset.js
  client/src/pages/signup.js
  server/index.js
  server/models/Users.js
Labels: documentation, enhancement, mongodb, express, react, styles, Main PBI, Sprint4

#83 Feat:Creating edit recipe page and functions
  client/src/App.css
  client/src/App.js
  client/src/pages/createRecipe.js
  client/src/pages/editRecipe.js
  client/src/pages/login.js
  client/src/pages/recipe.js
  server/index.js
Labels: enhancement, mongodb, express, react, styles, Sprint4

#80 feat: Added the explore page with the route for it and styled it
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/explore.js
  server/index.js
  server/models/Recipes.js
Labels: bug, documentation, enhancement, mongodb, express, react, Sprint4

#85 fix: Fixes total time calculation
  server/index.js
  server/models/Recipes.js
Labels: enhancement, mongodb, react, bug fix, Waiting on review, Sprint4

#86 feat: Implement recipe search
  client/src/App.css
  client/src/App.js
  client/src/pages/index.js
  client/src/pages/searchResult.js
  server/index.js
Labels: enhancement, high-priority, mongodb, react, styles, Sprint4

#88 feat: Alert on successful recipe upload and total time calculation
  client/src/pages/recipe.js
  server/index.js
  server/models/Recipes.js
Labels: enhancement, mongodb, express, react, bug fix, Main PBI, Sprint4

#89 feat: Implement recipe search
  client/src/App.css
  client/src/App.js
  client/src/pages/index.js
  client/src/pages/searchResult.js
  server/index.js
Labels: enhancement, high-priority, mongodb, react, styles, Main PBI, Sprint4

#90 bug: fixed console-log issues
  server/index.js
Labels: react, bug fix, Sprint4

#87 feat: Added the explore page and styled it to show 10 recipes
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/explore.js
  server/index.js
  server/models/Recipes.js
Labels: enhancement, express, react, styles, Main PBI, Sprint4

#91 Fix: recipe picture id
  server/index.js
Labels: bug fix, Sprint4

#84 Feat: Creating the edit recipe page with editing functions
  client/src/App.css
  client/src/App.js
  client/src/pages/createRecipe.js
  client/src/pages/editRecipe.js
  client/src/pages/login.js
  client/src/pages/recipe.js
  server/index.js
Labels: enhancement, mongodb, express, react, styles, Main PBI, Sprint4

#92 fix: Removes dead/un-needed components
  client/src/App.css
  client/src/components/Navbar/index.js
  client/src/pages/profile.js
  client/src/pages/signup.js
Labels: express, react, bug fix

#93 fix: Removes dead/un-needed components
  client/src/App.css
  client/src/components/Navbar/index.js
  client/src/pages/profile.js
  client/src/pages/signup.js
Labels: express, react, bug fix
