Repository COSC481W-2022Winter/capstone-gigabites, pull requests merged in 2022-03, with the labels that each got.

#17 feat: user-session
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/login.js
  server/index.js
Labels: documentation, enhancement, high-priority, sprint2, react

#18 feat: user-login
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/login.js
  server/index.js
Labels: enhancement, high-priority, sprint2, react

#20 feat: Logout button and navigation bar updates
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/components/logout.js
  client/src/pages/index.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/signup.js
Labels: documentation, enhancement, high-priority, sprint2, react

#22 feat:Adding and routing new pages
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/pages/config.json
  client/src/pages/editProfile.js
  client/src/pages/followers.js
  client/src/pages/following.js
  client/src/pages/ingredientSearch.js
  client/src/pages/logout.js
  client/src/pages/recipe.js
  client/src/pages/searchResults.js
Labels: enhancement, sprint2, react

#23 feat: Added recipe scheme and backend function for total time
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/components/logout.js
  client/src/pages/index.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/signup.js
  server/models/Recipes.js
Labels: enhancement, sprint2, mongodb

#25 fix: Bug of duplicate alerts on the login page
  client/src/pages/login.js
  client/src/pages/profile.js
Labels: documentation, sprint2, react, bug fix

#27 feat: Mgriffin navigation bar
  client/src/App.css
  client/src/App.js
  client/src/pages/editProfile.js
  client/src/pages/followers.js
  client/src/pages/following.js
  client/src/pages/index.js
  client/src/pages/ingredientSearch.js
  client/src/pages/login.js
  client/src/pages/logout.js
  client/src/pages/passwordReset.js
  client/src/pages/profile.js
  client/src/pages/recipe.js
  client/src/pages/searchResults.js
Labels: sprint2, react, bug fix

#21 feat: User sessions and logout button
  README.md
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/components/logout.js
  client/src/pages/index.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/signup.js
  server/index.js
Labels: bug, documentation, enhancement, sprint2, react, bug fix

#28 feat: User sessions and logout button
  README.md
  client/src/App.css
  client/src/App.js
  client/src/components/Navbar/index.js
  client/src/components/logout.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/signup.js
  server/index.js
Labels: documentation, enhancement, sprint2, react, bug fix

#30 feat: added buttons to profile page and styling
  client/src/App.css
  client/src/pages/profile.js
  server/models/Users.js
Labels: enhancement, sprint2, react, styles

#32 feat: Add recipe model
  client/src/App.css
  client/src/App.js
  client/src/pages/createRecipe.js
  server/index.js
  server/models/Recipes.js
Labels: enhancement, sprint2, mongodb, react, styles

#34 fix: Added commented untested function accidently removed in merge conflict
  server/models/Recipes.js
Labels: sprint2, mongodb

#33 feat: Create recipe and edit profile buttons
  client/src/App.css
  client/src/pages/profile.js
  server/models/Users.js
Labels: enhancement, sprint2, react, Main PBI

#36 feat: create recipe page
  client/src/App.css
  client/src/App.js
  client/src/pages/createRecipe.js
  client/src/pages/following.js
  client/src/pages/login.js
  client/src/pages/profile.js
  server/index.js
  server/models/Recipes.js
Labels: enhancement, sprint2, mongodb, react, styles, Main PBI

#44 feat: Profile image and bio on view-profile page
  client/src/App.css
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/user_images/default.gif
  server/index.js
  server/models/Users.js
Labels: enhancement, mongodb, react, sprint3, styles

#46 feat: Added username to recipe model schema
  client/src/pages/createRecipe.js
  server/models/Recipes.js
Labels: enhancement, high-priority, mongodb, react, sprint3, Waiting on review

#47 feat: Function to get recipes from backend
  client/src/pages/profile.js
Labels: enhancement, mongodb, react, sprint3

#51 feat: Ingredient Schema/Model on backend
  server/models/Ingredients.js
Labels: enhancement, high-priority, mongodb, sprint3, Main PBI

#48 feat: View logged in users recipes on profile page
  client/src/App.css
  client/src/App.js
  client/src/components/logout.js
  client/src/pages/createRecipe.js
  client/src/pages/loggedout.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/recipe_images/default2.png
  client/src/pages/signup.js
  client/src/pages/user_images/default.gif
  server/index.js
  server/models/Recipes.js
  server/models/Users.js
Labels: documentation, enhancement, mongodb, react, bug fix, sprint3, styles, Waiting on review

#52 fix: Merge error
  client/src/pages/login.js
Labels: react, bug fix, sprint3

#49 feat: View logged in users recipes on view profile page
  client/src/App.css
  client/src/App.js
  client/src/components/logout.js
  client/src/pages/createRecipe.js
  client/src/pages/loggedout.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/recipe_images/default2.png
  client/src/pages/signup.js
  server/index.js
  server/models/Recipes.js
  server/models/Users.js
Labels: documentation, enhancement, high-priority, mongodb, react, bug fix, sprint3, styles, Main PBI

#53 refractor: Need necessary functions from main
  client/src/App.css
  client/src/App.js
  client/src/components/logout.js
  client/src/pages/createRecipe.js
  client/src/pages/loggedout.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/recipe_images/default2.png
  client/src/pages/signup.js
  client/src/pages/user_images/default.gif
  server/index.js
  server/models/Ingredients.js
  server/models/Recipes.js
  server/models/Users.js
Labels: mongodb, react, sprint3

#54 Mgriffin edit user profile layout
  client/src/App.css
  client/src/pages/createRecipe.js
  client/src/pages/editProfile.js
  client/src/pages/login.js
  client/src/pages/profile.js
  client/src/pages/user_images/default.gif
  server/index.js
  server/models/Users.js
Labels: enhancement, mongodb, react, sprint3, styles
